apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-agent
  namespace: irestrict-security
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spire-agent
  namespace: irestrict-security
spec:
  selector:
    matchLabels:
      app: spire-agent
  template:
    metadata:
      labels:
        app: spire-agent
    spec:
      serviceAccountName: spire-agent
      hostPID: true
      containers:
        - name: spire-agent
          image: ghcr.io/spiffe/spire-agent:1.11.2
          args: ["-config", "/run/spire/config/agent.conf"]
          volumeMounts:
            - name: config
              mountPath: /run/spire/config
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
      volumes:
        - name: config
          configMap:
            name: spire-agent-config
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-agent-config
  namespace: irestrict-security
data:
  agent.conf: |
    agent {
      data_dir = "/run/spire/data"
      log_level = "INFO"
      server_address = "spire-server"
      server_port = "8081"
      trust_domain = "miva.local"
    }
    plugins {
      NodeAttestor "k8s_psat" {
        plugin_data {
          cluster = "miva-cluster"
        }
      }
      KeyManager "memory" {
        plugin_data {}
      }
      WorkloadAttestor "k8s" {
        plugin_data {}
      }
    }
