apiVersion: v1
kind: Namespace
metadata:
  name: miva-system
  labels:
    app.kubernetes.io/part-of: miva-zt-api-auth
---
apiVersion: v1
kind: Namespace
metadata:
  name: miva-identity
  labels:
    app.kubernetes.io/part-of: miva-zt-api-auth
---
apiVersion: v1
kind: Namespace
metadata:
  name: miva-security
  labels:
    app.kubernetes.io/part-of: miva-zt-api-auth
---
apiVersion: v1
kind: Namespace
metadata:
  name: miva-observability
  labels:
    app.kubernetes.io/part-of: miva-zt-api-auth
---
apiVersion: v1
kind: Namespace
metadata:
  name: miva-apps
  labels:
    app.kubernetes.io/part-of: miva-zt-api-auth
    istio-injection: enabled
