apiVersion: v1
kind: Namespace
metadata:
  name: irestrict-system
  labels:
    app.kubernetes.io/part-of: irestrict-v3
---
apiVersion: v1
kind: Namespace
metadata:
  name: irestrict-identity
  labels:
    app.kubernetes.io/part-of: irestrict-v3
---
apiVersion: v1
kind: Namespace
metadata:
  name: irestrict-security
  labels:
    app.kubernetes.io/part-of: irestrict-v3
---
apiVersion: v1
kind: Namespace
metadata:
  name: irestrict-observability
  labels:
    app.kubernetes.io/part-of: irestrict-v3
---
apiVersion: v1
kind: Namespace
metadata:
  name: irestrict-apps
  labels:
    app.kubernetes.io/part-of: irestrict-v3
    istio-injection: enabled
